version: '3'

networks:
  wordpressnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.69.16.0/27

services:
  db:
    image: mysql:5.7.27
    container_name: db
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      wordpressnet:
        ipv4_address: 172.69.16.8
  
  web:
    image: wordpress:5.3.0-apache
    container_name: web
    hostname: web
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE_KEY_SALT', 'bdt19.com');
        define('WP_CACHE', true);
        define('WP_REDIS_SENTINEL', 'mymaster');
        define('WP_REDIS_CLIENT', 'predis');        
        define('WP_REDIS_SERVERS', ['tcp://wordpress-redis_sentinel_1:26379/?alias=sen1', 'tcp://wordpress-redis_sentinel_2:26379/?alias=sen2', 'tcp://wordpress-redis_sentinel_3:26379/?alias=sen3']);      
    ports:
      - 8069:80
    networks:
      wordpressnet:
        ipv4_address: 172.69.16.6
  
  web_nocache:
    image: wordpress:5.3.0-apache
    container_name: web_nocache
    hostname: web_nocache
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress_nocache
      WORDPRESS_TABLE_PREFIX: wp_
    ports:
      - 8070:80
    networks:
      wordpressnet:
        ipv4_address: 172.69.16.7

  master:
    image: bitnami/redis:latest
    container_name: redis-master
    hostname: redis-master
    environment:
      REDIS_REPLICATION_MODE: master
      ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      wordpressnet:
        ipv4_address: 172.69.16.9

  slave:
    image: bitnami/redis:latest
    environment:
      REDIS_REPLICATION_MODE: slave
      REDIS_MASTER_HOST: redis-master
      ALLOW_EMPTY_PASSWORD: 'yes'
    depends_on:
      - master
    networks:
      - wordpressnet

  sentinel:
    image: bitnami/redis-sentinel:latest
    environment:
      REDIS_MASTER_HOST: redis-master
    depends_on:
      - master
    networks:
      - wordpressnet
